### PR TITLE
Added some awsome sections in your README.md

### PR DESCRIPTION
**Pull request by IIvexII**

### CODE REVIEW

**Review by IIvexII — COMMENTED** [review]
LGTM :tada:

**Comment by JanitaRiyaz** [comment]
Thank you so much for such customisation to my profile.

**Comment by IIvexII** [comment]
I saw you have just started your journey in *open source community*. Can you help me with documentation of this [repository](https://github.com/IIvexII/LGU-TimetableAPI) It would help me to focus on more technical part of that project while leaving the docs on you. *Don't worry* **if you don't know** `markdown language`. I will guide you as you progress.

**Comment by JanitaRiyaz** [comment]
> I saw you have just started your journey in _open source community_. Can you help me with documentation of this [repository](https://github.com/IIvexII/LGU-TimetableAPI) It would help me to focus on more technical part of that project while leaving the docs on you. _Don't worry_ **if you don't know** `markdown language`. I will guide you as you progress.

yeah surely! it will great plasure for me.. i'm working on some doucumentations and surely i'll happy to work with you.  :)

**Comment by IIvexII** [comment]
> yeah surely! it will great plasure for me.. i'm working on some doucumentations and surely i'll happy to work with you. :)

Thanks! I have created the [issue](https://github.com/IIvexII/LGU-TimetableAPI/issues/15) for you. Please read this short [Contribution guide](https://github.com/IIvexII/LGU-TimetableAPI/blob/main/CONTRIBUTING.md) for this project before proceeding any further

**Pull request merged**
